version: '3.7'
services:
  backend:
    image: gridgain/gridgain-web-console-backend:2020.03.01
    # Restart on crash.
    restart: always
    tty: true
    container_name: gridgain-webconsole-backend
    volumes:
      - ./gridgain-console-work:/opt/gridgain-web-console-server/work
    networks:
      - gridgain-net

  frontend:
    image: gridgain/gridgain-web-console-frontend:2020.03.01
    container_name: gridgain-webconsole-frontend
    tty: true
    depends_on:
      - backend
    networks:
      - gridgain-net
    ports:
      # Proxy HTTP nginx port (HOST_PORT:DOCKER_PORT)
      - 80:8008
      
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - "81:80"
    networks:
      - gridgain-net
    tty: true
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
networks:
  gridgain-net:
    driver: bridge
